"""Initial migration

Revision ID: a4fa170f97e2
Revises: 
Create Date: 2022-01-05 23:04:26.406704

"""
from alembic import op
import sqlalchemy as sa
import ormar

# revision identifiers, used by Alembic.
revision = 'a4fa170f97e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('count_of_subscribers', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_added_at'), 'channels', ['added_at'], unique=False)
    op.create_table('users',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_register_at'), 'users', ['register_at'], unique=False)
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('channel_id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('rate', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='fk_rates_channels_id_channel_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_rates_users_id_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uc_rates_user_id_channel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    op.drop_index(op.f('ix_users_register_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_channels_added_at'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
